@baseUrl = {{$dotenv HOST}}:{{$dotenv AUTH_PORT}}/auth
@requestUrl = {{baseUrl}}/v1
@token = {{login.response.body.token}}

###
GET {{baseUrl}}/health

###
# @name login
POST {{requestUrl}}/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###

# @name logout
POST {{requestUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "token": "{{token}}"
}
