@loginUrl = {{$dotenv HOST}}:{{$dotenv AUTH_PORT}}/auth/v1/login
@baseUrl = {{$dotenv HOST}}:{{$dotenv USERS_PORT}}/users
@requestUrl = {{baseUrl}}/v1
@token = {{login.response.body.token}}
@id = {{post.response.body.id}}

###
GET {{baseUrl}}/health

###
# @name login
POST {{loginUrl}
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###
GET {{requestUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{requestUrl}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
###
# @name post
POST {{requestUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "login": "teste",
  "password": "teste",
  "roles": "USER"
}
###
PUT {{requestUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}",
  "name": "pipoca",
  "breed": "pipoca",
  "age": 4
}
###
DELETE {{requestUrl}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}