FROM node:20-alpine as build

WORKDIR /app

COPY /dist/src/microservices/auth/src ./

# Install PM2
RUN npm install -g pm2

#RUN npm i -g @nestjs/cli
#RUN npm ci --omit=dev --ignore-scripts
#RUN npm run build

# clear application caching
RUN npm cache clean --force

RUN ls /app -al

# CMD [ "npm", "run", "start" ]
CMD [ "node", "/app/main" ]