version: '2'
services:
  auth:
    container_name: auth
    #image: node:20-alpine
    build:
      context: .
      dockerfile: ../apps/auth/Dockerfile
    #restart: always
    env_file:
      - ../.env
    ports:
      - '3100:3100'
    #volumes:
    #  - ../dist/src/microservices/auth/src:/app
    #command: node /app/main
    networks:
      - internal

networks:
  internal:
    driver: bridge
    external: true
