version: '3'

volumes:
  users-mongo-data:

networks:
  users-network:
    driver: bridge

services:
  users-mongo:
    container_name: users-mongo
    image: mongo:latest
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: admin
    # ports:
    #   - '27017:27017'
    volumes:
      - users-mongo-data:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint/initdb.d/mongo-init.sh
    command: --auth
    networks:
      - users-network

  users-mongo-express:
    container_name: users-mongo-express
    image: mongo-express
    ##restart: always
    ports:
      - '8081:8081'
    environment:
      #ME_CONFIG_MONGODB_SERVER: users-mongo
      #ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@users-mongo:27017/?authSource=admin
    links:
      - users-mongo
    depends_on:
      - users-mongo
    networks:
      - users-network

  users:
    container_name: users
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    env_file:
      - ../.env
    ports:
      - '3101:3101'
    #volumes:
    #  - ../dist/src/microservices/auth/src:/app
    #command: node /app/main
    networks:
      - users-network
