version: '3'

volumes:
  cats-postgres-data:

networks:
  cats-network:
    driver: bridge

services:
  cats:
    container_name: cats
    build:
      context: .
      dockerfile: ./Dockerfile
    #restart: always
    env_file:
      - ../.env
    ports:
      - '3101:3101'
    #volumes:
    #  - ../dist/src/microservices/auth/src:/app
    #command: node /app/main
    networks:
      - cats-network
